- hosts: all
  become: yes
  tasks:
    - name: Atualizar cache de pacotes APT no Linux
      apt:
        update_cache: yes

    - name: Instalar dependências essenciais (Git, Python, Pip, Docker)
      apt:
        name:
          - git
          - curl
          - python3-pip
          - python3-venv
          - docker.io
        state: present

    # Configuração específica para a VM do Simulador (Gerador de Dados)
    - name: Criar diretório de trabalho para o Simulador de Dados da FCA
      file:
        path: /opt/fca/simulator
        state: directory
        mode: '0755'

    # Configuração específica para a Camada de Armazenamento / Big Data
    - name: Criar diretórios de armazenamento e logs do pipeline
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/fca/data/raw
        - /opt/fca/data/processed
        - /opt/fca/logs
