[simulator]
vm-simulator ansible_host=192.168.122.10 ansible_user=gabriel

[etl]
vm-etl ansible_host=192.168.122.11 ansible_user=gabriel

[bigdata]
vm-bigdata ansible_host=192.168.122.12 ansible_user=gabriel

[monitoring]
vm-monitoring ansible_host=192.168.122.13 ansible_user=gabriel

[all:vars]
ansible_python_interpreter=/usr/bin/python3