[simulator]
vm-simulator ansible_host=192.168.122.92

[etl]
vm-etl ansible_host=192.168.122.102

[bigdata]
vm-bigdata ansible_host=192.168.122.178

[monitoring]
vm-monitoring ansible_host=192.168.122.204

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa