[simulador]
vm-simulador ansible_host=192.168.1.10 ansible_user=ubuntu

[r_pipeline]
vm-r ansible_host=192.168.1.11 ansible_user=ubuntu

[big_data]
vm-bigdata ansible_host=192.168.1.12 ansible_user=ubuntu

[monitoramento]
vm-monitoramento ansible_host=192.168.1.13 ansible_user=ubuntu
