[bigdata]
vm-bigdata ansible_host=192.168.122.37

[etl]
vm-etl ansible_host=192.168.122.112

[monitoring]
vm-monitoring ansible_host=192.168.122.139

[simulator]
vm-simulator ansible_host=192.168.122.176

[all:vars]
ansible_user=aluno
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa